apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-techtrends
  name: python-techtrends
  namespace: default 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-techtrends
    spec:
      containers:
      - image: mert436/techtrends 
        imagePullPolicy: IfNotPresent
        name: python-techtrends
        resources:
          requests:
            cpu: 50m
            memory: 256Mi